### ISSUE TITLE
WIFI not working

### ISSUE THREAD

**Issue by dongxicc** [ubports-oneplus5/documentation#2]
OnePlus 5T 
I install using Erfan GSI and wifi not working

**Comment by JamiKettunen** [comment]
You need to `sudo insmod wlan.ko` which you can find under the kernel build arfifact folder; it could perhaps be helped by [ignoring all "module magic" mismatches](https://github.com/erfanoabdi/android_kernel_motorola_sdm632/commit/a1d16bf0f1dd79f1d693b690e49a80447b1fc0bb) so you can load the module already present in `/vendor/lib/modules/`, but I've not worked on this project for quite a while now.

For WLAN to work after boot you need to create a service file in `/usr/share/upstart/sessions/wlan-insmod.conf` that loads the kernel module like so:
```
description "Load the WLAN module"

start on started dbus
stop on stopping dbus

exec insmod /path/to/wlan.ko
```
And to actually enable the service run `ln -s /usr/share/upstart/sessions/wlan-insmod.conf /etc/init/`.

**Comment by JamiKettunen** [comment]
In case you're still interested, please see the official and now merged sources @ https://github.com/Halium/halium-devices/pull/275; I'm archiving this whole project. CI for system/vendor images for 5/5T should appear later.
