### ISSUE TITLE
Phone stuck in bootloop after installing

### ISSUE THREAD

**Issue by ghost** [ubports-oneplus5/documentation#4]
Pop!OS 20.10 (based on Ubuntu 20.10), Oneplus 5, did everything exactly as in the docs using the GSI installer, after doing all the steps and rebooting the device is stuck in a bootloop. I'd be happy to provide any logs but I have no idea where they might be.

I also had success installing Sailfish OS before on this phone, if this helps.

**Comment by ghost** [comment]
I forgot to mention that I had to modify the manifest to get the boot image to build. It needed an oppo common device tree, so i added one.
Lines I added:
```
<remote name="los" fetch="https://github.com/LineageOS" revision="lineage-16.0"/>
<project path="device/oppo/common" name="android_device_oppo_common" remote="los"/>
```

**Comment by JamiKettunen** [comment]
Expect nothing under this org to be usable anymore; I'll deprecate and most likely remove these all when [Flohack's repos](https://github.com/Flohack74?tab=repositories) get migrated to the [UBports GitHub](https://github.com/ubports) (if they do).

If you want to test that port, here's the manifest I use:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<manifest>

	<remote name="florian" fetch="https://github.com/Flohack74" revision="halium-9.0" />

	<!-- Linux kernel 4.4 (Android) -->
	<project path="kernel/oneplus/msm8998" name="android_kernel_oneplus_msm8998" remote="florian" />

	<!-- Device configuration -->
	<project path="device/oneplus/msm8998-common" name="android_device_oneplus_msm8998-common" remote="florian" />
	<project path="device/oneplus/cheeseburger"   name="android_device_oneplus_cheeseburger"   remote="florian" />
	<project path="device/oneplus/dumpling"       name="android_device_oneplus_dumpling"       remote="florian" />

	<!-- Vendor blobs -->
	<project path="vendor/oneplus" name="sailfishos-oneplus5/proprietary_vendor_oneplus-msm8998" />

</manifest>
```
You need to run `halium/devices/setup oneplus5` after saving the above manifest in `halium/devices/manifests/oneplus_oneplus5.xml`.

**Comment by ghost** [comment]
Thank you! I was able to successfully compile the boot image with this manifest!

**Comment by JamiKettunen** [comment]
I recommend building the systemimage as well and deploying it alongside [an ARM64 rootfs](https://ci.ubports.com/job/xenial-hybris-android9-rootfs-arm64/) with [JBB's halium-install](https://gitlab.com/JBBgameich/halium-install) as a bunch of device specifics are being worked on currently; that way if you also find some fixes that can be applied on a systemimage / overlay level, you could make a PR on [Flohack's repos](https://github.com/Flohack74?tab=repositories) :)

**Comment by ghost** [comment]
Also, where can I ask questions about building the systemimage? I'm getting some java build errors and couldn't find any useful info on them.

**Comment by JamiKettunen** [comment]
@Astrr ah, my instructions weren't clearly really good; try saving the manifest into `halium/devices/manifests/oneplus_cheeseburger.xml` instead and run `ln -s oneplus_cheeseburger.xml halium/devices/manifests/oneplus_dumpling.xml` to create a symlink (in case you intend to build for the 5T) and use `halium/devices/setup <cheeseburger|dumpling>`
After that you also have to run `hybris-patches/apply-patches.sh --mb` before `mka systemimage` as per the [Halium 9 wiki](https://github.com/ubports/porting-notes/wiki/Halium-9)

**Comment by ghost** [comment]
@JamiKettunen So, I was able to successfully install everything (flashed the boot image, ran halium-install with rootfs and the systemimage) and ssh into the phone, however, when I try to run
 `cat /var/lib/lxc/android/rootfs/ueventd*.rc /vendor/ueventd*.rc | grep ^/dev | sed -e 's/^\/dev\///' | awk '{printf "ACTION==\"add\", KERNEL==\"%s\", OWNER=\"%s\", GROUP=\"%s\", MODE=\"%s\"\n",$1,$3,$4,$2}' | sed -e 's/\r//' >/etc/udev/rules.d/70-$DEVICE.rules` to generate udev rules 
 I get `cat: '/var/lib/lxc/android/rootfs/ueventd*.rc': No such file or directory`
I checked the rootfs folder, it's completely empty. How can I fix that?

**Comment by JamiKettunen** [comment]
@Astrr [udev rules are already in place](https://github.com/Flohack74/android_device_oneplus_msm8998-common/blob/halium-9.0/ubuntu/70-dumpling.rules) (as are most things already with this port), no need to generate them. Are you sure the the device folders you've got cloned match Florian's repos?

**Comment by ghost** [comment]
@JamiKettunen yep, all the folders match. I also tried completely deleting the Halium folder and doing everything again, but after repeating all the steps the phone still doesn't boot to unity and the rootfs folder is still empty.

**Comment by JamiKettunen** [comment]
@Astrr think I know what's happening: you're not using the `-s` flag with `halium-install`; it is needed on all Halium 9 ports. The command I use is `./halium-install -s -p ut ubuntu-touch-android9-arm64.tar.gz "$OUT/system.img"` after building systemimage

**Comment by ghost** [comment]
@JamiKettunen oh, right, you're absolutely correct, everything works now! Thanks a lot to you for the support and your contributions (and to Florian too!), you're awesome!
