### ISSUE TITLE
Could not compile boot image from source

### ISSUE THREAD

**Issue by ubuntu2029** [ubports-oneplus5/documentation#5]
thomas@template:~/Halium$ breakfast dumpling
including vendor/lineage/vendorsetup.sh
build/target/product/verity.mk:30: error: _nic.PRODUCTS.[[device/oneplus/dumpling/lineage_dumpling.mk]]: "device/oppo/common/common.mk" does not exist.
01:51:30 dumpvars failed with: exit status 1
Device dumpling not found. Attempting to retrieve device repository from LineageOS Github (http://github.com/LineageOS).
Found repository: android_device_oneplus_dumpling
Default revision: lineage-16.0
Checking branch info
Checking if device/oneplus/dumpling is fetched from android_device_oneplus_dumpling
Adding dependency: LineageOS/android_device_oneplus_dumpling -> device/oneplus/dumpling
Using default branch for android_device_oneplus_dumpling
Syncing repository to retrieve project.
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
fatal: duplicate path kernel/oneplus/msm8998 in /home/thomas/Halium/.repo/manifest.xml
Repository synced!
Looking for dependencies in device/oneplus/dumpling
Adding dependencies to manifest
Checking if device/oneplus/msm8998-common is fetched from android_device_oneplus_msm8998-common
Adding dependency: LineageOS/android_device_oneplus_msm8998-common -> device/oneplus/msm8998-common
Using default branch for android_device_oneplus_msm8998-common
Syncing dependencies
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
fatal: duplicate path kernel/oneplus/msm8998 in /home/thomas/Halium/.repo/manifest.xml
Looking for dependencies in device/oneplus/msm8998-common
Looking for dependencies in device/oppo/common
device/oppo/common has no additional dependencies.
Looking for dependencies in kernel/oneplus/msm8998
kernel/oneplus/msm8998 has no additional dependencies.
Done
build/target/product/verity.mk:30: error: _nic.PRODUCTS.[[device/oneplus/dumpling/lineage_dumpling.mk]]: "device/oppo/common/common.mk" does not exist.
01:51:40 dumpvars failed with: exit status 1
build/target/product/verity.mk:30: error: _nic.PRODUCTS.[[device/oneplus/dumpling/lineage_dumpling.mk]]: "device/oppo/common/common.mk" does not exist.
01:51:40 dumpvars failed with: exit status 1

** Don't have a product spec for: 'lineage_dumpling'
** Do you have the right repo manifest?

**Comment by ubuntu2029** [comment]
I tried to create a new folder named oppo and download file from https://codeload.github.com/LineageOS/android_device_oppo_common/zip/lineage-16.0.

**Comment by ubuntu2029** [comment]
including vendor/lineage/vendorsetup.sh
Trying dependencies-only mode on a non-existing device tree?

============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=9
LINEAGE_VERSION=16.0-20210113-UNOFFICIAL-dumpling
TARGET_PRODUCT=lineage_dumpling
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=cortex-a73
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv8-a
TARGET_2ND_CPU_VARIANT=cortex-a73
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-4.19.0-13-amd64-x86_64-Debian-GNU/Linux-10-(buster)
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=PQ3A.190801.002
OUT_DIR=/home/thomas/Halium/out
PRODUCT_SOONG_NAMESPACES= hardware/qcom/audio-caf/msm8998 hardware/qcom/display-caf/msm8998 hardware/qcom/media-caf/msm8998



thomas@template:~/Halium$ mka halium-boot
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=9
LINEAGE_VERSION=16.0-20210113-UNOFFICIAL-dumpling
TARGET_PRODUCT=lineage_dumpling
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=cortex-a73
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv8-a
TARGET_2ND_CPU_VARIANT=cortex-a73
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-4.19.0-13-amd64-x86_64-Debian-GNU/Linux-10-(buster)
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=PQ3A.190801.002
OUT_DIR=/home/thomas/Halium/out
PRODUCT_SOONG_NAMESPACES= hardware/qcom/audio-caf/msm8998 hardware/qcom/display-caf/msm8998 hardware/qcom/media-caf/msm8998
============================================
[1/1] /home/thomas/Halium/out/soong/.minibootstrap/minibp /home/thomas/Halium/out/soong/.bootstrap/build.ninja
[54/55] glob prebuilts/ndk/cpufeatures.bp
[76/77] /home/thomas/Halium/out/soong/.bootstrap/bin/soong_build /home/thomas/Halium/out/soong/build.ninja


It seems like that I can compile it from source code, but the halium-boot could not be used for boot. It is in the loop process. No usb can be detected by linux box or windows box? Anything wrong or what steps should i follow?

**Comment by JamiKettunen** [comment]
Please use the official and now merged sources @ https://github.com/Halium/halium-devices/pull/275; I'm archiving this whole project.
